# Generated by Django 4.2.3 on 2023-07-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
